[target.x86_64-apple-darwin]
#rustflags = ["-C", "target-cpu=native", "-C", "link-arg=-mmacosx-version-min=11.0"]
rustflags = ["-C", "link-arg=-mmacosx-version-min=11.0"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-mmacosx-version-min=11.0"]


[target.x86_64-unknown-linux-musl]
linker = "x86_64-linux-musl-gcc"
